on: [push, pull_request]
name: All Checks
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential llvm clang libclang-dev
      - name: capstone from source
        run: |
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar xf 4.0.2.tar.gz
          cd capstone-4.0.2
          make -j 8
          sudo make install
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - run: rustup component add rustfmt
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings