on: [push, pull_request]
name: All Checks
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential llvm clang libclang-dev
      - name: capstone from source
        run: |
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar xf 4.0.2.tar.gz
          cd capstone-4.0.2
          make -j 8
          sudo make install
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: cargo test
        run: cargo test
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy -- -D warnings
